team10/accounts/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy, include
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import *

app_name = 'accounts'

urlpatterns = [
    # 추가적인 URL 설정을 필요에 따라 작성하세요.
    path('login/', auth_views.LoginView.as_view(), name='login'),  # 로그인 URL 설정
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),  # 회원가입 URL 설정
    path('signup/', views.signup, name='signup'),
    path("profile", views.profile, name='profile'),
    path("password/", views.MyPasswordChangeView.as_view(), #success_url을 view에 작성하는 것으로 바꿈
         name="password_change"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path('update/', views.update, name="profile_update"),
]

team10/brd/urls.py
from django.urls import path
from . import views
from .views import search_view

app_name = 'brd'

urlpatterns = [
    path('', views.list, name='notice_board'), 
    path('', views.list, name='list'),
    path('search/', search_view, name='search'),  # 검색 URL 패턴을 추가합니다.
    path('<int:no>/', views.detail, name='detail'),
    path('update/<id>/', views.post_update , name='update'),
    path('delete/<id>/', views.post_delete , name='delete'), 
    path('new/', views.post_create, name='create'),
    path('<int:pk>/comments/', views.comments_create, name="comments_create"),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name="comments_delete"),
]

team10/home/urls.py
# home/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views
from .views import home_view
from django.contrib import admin

app_name = 'home'

urlpatterns = [
    path('', home_view, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('intro/', views.intro, name='intro'),
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('brd/', include('brd.urls')),
    path('service/', include('service.urls')),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('terms-of-service/', views.terms_of_service, name='terms_of_service'),
    path('data-policy/', views.data_policy, name='data_policy'),
]

team10/service/urls.py
from django.urls import path
from . import views


app_name = 'service'  # 앱 이름 설정

urlpatterns = [
    path('service/', views.service, name='service'),
    path('statistics/', views.statistics, name='statistics'),
    path('game/', views.game, name='game'), 
    path('send_image/', views.send_image, name='send_image'),
    path('send_image_game/', views.send_image_game, name='send_image_game'),
]

team10/team10/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),  # 'home' 앱이 메인 페이지
    path('accounts/', include('accounts.urls')),
    path('brd/', include('brd.urls')),
    path('service/', include('service.urls')),
    path('accounts/', include('allauth.urls')),
    path('chatbot/', include('chatbot.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team10/templates/layout.html
{% load static %}
<!DOCTYPE HTML>
<html lang="ko"> <!-- 코드언어 표시 == 웹 표준지침 준수 -->
	<head>
		<title>바른자세 회사소개</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<link rel="icon" href="{% static 'assets/images/logo_page.png' %}" type="image/x-icon" />
	</head>
	<body class="single is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<h1><a href="{% url 'home:home' %}"><img src="{% static 'assets/images/logo_page.png' %}"style="width:45px; height:auto;"></a></h1>
						<nav class="links">
							<ul>
								{% if not user.is_authenticated %}
									<li><a href="{% url 'accounts:login' %}?next={{request.path}}">로그인</a></li>
									<li><a href="{% url 'accounts:signup' %}?next={{request.path}}">회원가입</a></li>
								{% else %}
									<li><a href="{% url 'accounts:profile' %}">{{user}}님!</a></li>
									<li><a href="{% url 'accounts:logout' %}?next={{request.path}}">로그 아웃</a></li>
									<li class="menu-item-board"><a href="{% url 'brd:notice_board' %}">게시판</a></li>
									<li><a href="{% url 'service:service' %}">서비스</a></li>
								{% endif %}
								<li class="menu-item-company"><a href="{% url 'home:intro' %}">회사소개</a></li>
							</ul>
						</nav>
						<nav class="main">
							<ul>
								<li class="search">
									<a class="fa-search" href="#search">Search</a>
									<form id="search" method="get" action="#">
										<input type="text" name="query" placeholder="Search" />
									</form>
								</li>
								<li class="menu">
									<a class="fa-bars" href="#menu">Menu</a>
								</li>
							</ul>
						</nav>
					</header>

				<!-- Menu -->
					<section id="menu">

						<!-- Search -->
							<section>
								<form class="search" method="get" action="#">
									<input type="text" name="query" placeholder="Search" />
								</form>
								<script>
									document.addEventListener('DOMContentLoaded', function() {
										// 검색 폼 제출 이벤트 리스너 추가
										document.querySelector('.search').addEventListener('submit', function(event) {
											event.preventDefault(); // 기본 제출 동작 방지
											var query = document.querySelector('.search input[name="query"]').value; // 검색어 가져오기
											redirectToPageBasedOnQuery(query); // 검색 처리 함수 호출
										});
									});
								
									function redirectToPageBasedOnQuery(query) {
										if (query.includes('통계 결과', '통계', '기록')) {
											window.location.href = '{% url "service:statistics" %}';
										} else if (query.includes('모니터링', '서비스', '카메라')) {
											window.location.href = '{% url "service:service" %}';
										} else if (query.includes('게시판')) {
											window.location.href = '{% url "brd:notice_board" %}';
										} else if (query.includes('회사소개')) {
											window.location.href = '{% url "home:intro" %}';
										} else if (query.includes('회원가입')) {
											window.location.href = '{% url "accounts:signup" %}';
										} else if (query.includes('게임')) {
											window.location.href = '{% url "service:game" %}';
										} else {
											// 다른 검색어에 대한 처리 (옵션)
											// 예: window.location.href = '/search?query=' + encodeURIComponent(query);
										}
									}
								</script>
							</section>

						<!-- Links -->
							<section>
								<ul class="links">
									<li>
										<a href="{% url 'service:service' %}">
											<h3>모니터링</h3>
											<p>당신의 자세에 대해 분석해보세요</p>
										</a>
									</li>
									<li>
										<a href="{% url 'service:statistics' %}">
											<h3>통계 결과</h3>
											<p>다양한 통계 결과를 시각화 해보세요</p>
										</a>
									</li>
									<li>
										<a href="{% url 'brd:notice_board' %}">
											<h3>게시판</h3>
											<p>결과를 다른 사람들과 비교해 보고 질문해 보세요</p>
										</a>
									</li>
								</ul>
							</section>
					</section>

                    {% block content %}
                    {% endblock %}

				<!-- Footer -->
				<section id="footer">
					<div class="footer-logo">
						<img src="{% static 'assets/images/logo_page.png' %}" alt="바른자세 로고" />
					</div>
					<ul class="icons">
						<li><a href="https://twitter.com" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="https://facebook.com" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
						<li><a href="https://instagram.com" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="mailto:your@email.com" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
					</ul>
					<div class="policy-links">
						| <a href="javascript:void(0);" onclick="openPrivacyPolicy();">개인정보처리방침</a>
						| <a href="javascript:void(0);" onclick="openTermsOfService();">이용약관</a>
						| <a href="javascript:void(0);" onclick="openFaq();">자주묻는질문</a>
						| <a href="javascript:void(0);" onclick="openDataPolicy();">데이터베이스이용약관</a> |
					</div>
					<script>
						function openPrivacyPolicy() {
							window.open('{% url 'home:privacy_policy' %}', 'Privacy Policy', 'width=600,height=400');
						}
						
						function openTermsOfService() {
							window.open('{% url 'home:terms_of_service' %}', 'Terms of Service', 'width=600,height=400');
						}

						function openDataPolicy() {
							window.open('{% url 'home:data_policy' %}', 'Data Policy', 'width=600,height=400');
						}
					</script>						
					<p class="copyright">
						<a href="https://aivle.edu.kt.co.kr/home/main/goMenuPage?mcd=MC00000034">KT Aivle School</a> Designed by Aivle 4기 10조.
					</p>
				</section>

		</div>

	<!-- Scripts -->
		<script src="{% static 'assets/js/jquery.min.js' %}"></script>
		<script src="{% static 'assets/js/browser.min.js' %}"></script>
		<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
		<script src="{% static 'assets/js/util.js' %}"></script>
		<script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>